### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhyzhkea** [powerbi-cli/powerbi-cli#25]
**Versions**:
-   **pbicli version**: 1.1.0
-   **nodejs version**: 15.7.0
-   **os name/version**: Windows 10 Enterprise 10.0.18363 

**Describe the bug**

"pbicli xmla query" fails with error "self signed certificate in certificate chain" using "pbicli login --xmla --service principal" while
"pbicli dataset refresh show --workspace" works

**To Reproduce**

1. Create Application Registration with Secret
2. Add "Power BI Service" via "API permissions" to App Registration
3. Add App Registration to Premium Workspace as Admin
4. Login using "pbicli login --xmla --service principal -p <app id> -s <secret> -t <tenant id>
5. Run pbicli dataset refresh show --workspace "<workspace name>" --dataset "<dataset name>"
-> successful

6. Run  "pbicli xmla query --connection "powerbi://api.powerbi.com/v1.0/myorg/<workspace name>" --dataset "<dataset name>" --script refresh.xmla --debug --verbose"
-> fails with "Request: Error: self signed certificate in certificate chain"

**Expected behavior**
TMSL script successfully executed

**Screenshots**

**Comment by liprec** [comment]
Thanks for reporting this and I will take a look what is causing this.

**Comment by liprec** [comment]
Will not be fixed as `xmla` command is deprecated with v1.2 and the official support for the `pbicli dataset query` command (https://docs.microsoft.com/en-us/rest/api/power-bi/datasets/execute-queries)
