### ISSUE TITLE
Need a format of json and give some sample for each command

### ISSUE THREAD

**Issue by PratheebanT** [powerbi-cli/powerbi-cli#26]
pbicli dataset parameter update
Update the parameters of a Power BI dataset

pbicli dataset parameter list [--workspace] [-w]
                              [--dataset] [-d]
                              [--parameter]
                              [--parameter-file]

The above statement is we need to use **update** instead of **list**. Update the CLI reference page.
Also i need --parameter sample and --parameter-file sample is required

If i am using --parameter-file getting below issue
Dataset Parameters list is invalid in **workspaceid**. Reason: Empty

Below format json file i am passing
{
"updateDetails": [
{
"name": "DatabaseName",
"newValue": "NewDB"
},
{
"name": "Servername",
"newValue": "Newtestserver"
}
]
}

Also required sample for

**Comment by liprec** [comment]
Documentation is updated to reflect this error.
