### ISSUE TITLE
[BUG] pbicli gateway datasource update FAILURE

### ISSUE THREAD

**Issue by yakluoto** [powerbi-cli/powerbi-cli#27]
gateway datasource update fails

See the sent request:

request: WebResource {
    streamResponseBody: undefined,
    url: 'https://api.powerbi.com/v1.0/myorggateways/<guid1>/datasources/<guid2>',
    method: 'PATCH',
    headers: HttpHeaders { _headersMap: [Object] },
    body: '{"type":"Buffer","data":[xxxxx]}',
    query: undefined,
    formData: undefined,
    withCredentials: false,
    abortSignal: undefined,
    timeout: 0,
    onUploadProgress: undefined,
    onDownloadProgress: undefined,
    proxySettings: undefined,
    keepAlive: undefined,
    agentSettings: undefined,
    redirectLimit: undefined
  },

This request has two problems:

1. Request URL is missing / between myorg and gateways
2. Data read from the file passed with the --credential-file parameter is not parsed to JSON, but instead passed as Buffer

Problem 2. is also at least present with the pbicli dataset refresh update command.

**Comment by liprec** [comment]
Fixed in v1.2 which will be released soon
