### ISSUE TITLE
[BUG] Workspace scan: cannot parse JSON. SyntaxError

### ISSUE THREAD

**Issue by Marco-Santoni** [powerbi-cli/powerbi-cli#31]
**Versions**:

-   **pbicli version**: 1.2.0
-   **nodejs version**: 6.13.4 (npm)
-   **os name/version**: Windows 10

**Describe the bug**
I'm trying to run

```powershell
pbicli admin workspace scan  --workspace-file file.json
SyntaxError: Unexpected token � in JSON at position 0
```

Where the `file.json` has the following content

```bash
{"workspaces": ["ec744b1b-da90-48b9-82e1-03692cb816bb"]}
```

**Expected behavior**
Invoke the `GetInfo` API as expected parsing the file.

**Comment by liprec** [comment]
Thanks for the PR and it is included in the new version v1.2.1
