### ISSUE TITLE
[BUG] Add viewer role to workspace

### ISSUE THREAD

**Issue by JulianMar11** [powerbi-cli/powerbi-cli#33]
**Versions**:

-   **pbicli version**: 1.2.1

**Describe the bug**

Access right assignment is not possible for Viewer.

pbicli workspace user add -w $workspaceId --access-right Viewer --identifier $objectId --principal-type Group

leads to
error: incorrect option 'Viewer'. Allowed values: Admin, Contributor, Member

I assume the new role needs to be allowed here:
https://github.com/powerbi-cli/powerbi-cli/blob/71ad22077901d84abe10e772ae7de8d4b5c4e77e/src/lib/helpers.ts#L38

**Comment by liprec** [comment]
Thanks for the feedback and it will be fixed in the next upcoming release.

**Comment by liprec** [comment]
Is fixed in the latest version: v1.3.
