### ISSUE TITLE
[BUG] dataset dax query method returns an error

### ISSUE THREAD

**Issue by DataGobes** [powerbi-cli/powerbi-cli#34]
**Versions**:

-   **pbicli version**:   pbicli      1.2.1
-   **nodejs version**:   npm@8.11.0
-   **os name/version**:   Microsoft Windows [Version 10.0.19044.1826]

**Describe the bug**
Error message when using query method on a dataset

pbicli dataset query --workspace "Alfred [Test]" --dataset "Sourcing - Inventory and Material Overview" --dax "EVALUATE(VALUES('Tables Used'))"

returns

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

**To Reproduce**

Use the dataset query method

**Expected behavior**
Returns dax query results

**Comment by liprec** [comment]
Thanks for the feedback and it will be fixed in the next upcoming release.

**Comment by liprec** [comment]
Is fixed in the latest version: v1.3.
