### ISSUE TITLE
[BUG] Always get missing gateway error when updating dataset gateway

### ISSUE THREAD

**Issue by cambeattydev** [powerbi-cli/powerbi-cli#35]
**Versions**:

-   **pbicli version**:1.2.1
-   **nodejs version**: v16.16.0
-   **os name/version**: Windows 10/ 10.0.19044 Build 19044

**Describe the bug**
When running `pbicli dataset gateway update -w {workspaceId} -d {datasetId} --gatewayId {gatewayIdOrGatewayName} --datasourceIds {listOfDataSourceIds}
` user will always get 

> error: missing option '--gateway'

If user tries to replace gatewayId with the `--gateway {gatewayIdOrGatewayName}` parameter user gets the following error

> unknown option '--gateway'. 

**To Reproduce**
1) Get or create workspace
2) Get or create dataset
3) Get or create gateway
4) Get or create dataSource on gateway from step 3
5) Run `pbicli dataset gateway update -w {workspaceId} -d {datasetId} --gatewayId {gatewayIdOrGatewayName} --datasourceIds {listOfDataSourceIds}` with info found in previous steps

**Expected behavior**
Dataset gateway is updated with no errors

**Comment by liprec** [comment]
Thanks for the feedback and it will be fixed in the next upcoming release.

**Comment by liprec** [comment]
Is fixed in the latest version: v1.3.
