### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shanerowley-ds** [powerbi-cli/powerbi-cli#42]
**Versions**:

-   **pbicli version**: 1.3.2
-   **nodejs version**: 8.15.0
-   **os name/version**: Windows 11 Home/21H2/22000.1219

**Describe the bug**
Importing DataFlows seems to do nothing.

**To Reproduce**
[1] Create a Power BI Workflow via Power BI in Web Browser
[2] Import a DataFlow from a JSON file to verify the file works without issue and can be imported.
[3] Delete the DataFlow from the WorkFlow
 N.B. Step 2 and 3 re unnecessary if you know you Dataflow JSON file already works
[4] Follow the instructions here to import a DataFlow: https://powerbi-cli.github.io/content/reference-import.html#pbicli-import-dataflow
[5] Open PowerShell (with admin rights, etc)
[6] Run (with appropriate file names)
    ```
    $testDataFlowFile = "C:\Documents\TestDataFlow.json"
    $testDataSetFile = "C:\Documents\TestDataSet.pbix"
    
    $workFlowName = "DataFlow ImportTest A"
    
    pbicli login 
    
    #Doesn't work 
    pbicli import dataflow -w $workFlowName --file $testDataFlowFile --debug
    
    #Works flawlessly
    pbicli import pbix -w $workFlowName --file $testDataSetFile --verbose --debug -o
```
[7] The only feedback I get is
```
Upload a Power BI import (C:\Documents\TestDataFlow.json)
Check if stored token is not expired
```
Although it will error if a DataFlow already exists on the WorkFlow or the JSON file path is incorrect
[8] Go to PowerBI in your Web Browser, open the WorkFlow, observe the DataSet has been imported without issue. But the DataFlow is nowhere to be seen.

**Expected behavior**
A PowerBI CLI or the Power BI API to actually work when issued a command to import a DataFlow, as per both PowerBI CLI documentation and/or PowerBI Api documentation, or the documentation to cover an actual working method of how to import/upload/create-from-file DataFlows via command line or API HTTP request.

**Comment by liprec** [comment]
Hi @shanerowley-ds,

Thanks for the feedback and you cannot overwrite an existing dataflow via the `import` command: the two `nameConflict` options for dataflows are `Abort` (default) and `GenerateUniqueName` and not overwrite.

If you want to update an existing dataflow, you should use the `pbicli dataflow update -w $workFlowName -f $dataflowName --update @$testDataFlowFile` command.

But I will update the documentation/help to emphasis that the command is only capable of importing **new** dataflows.

**Comment by shanerowley-ds** [comment]
If it was unclear, I'm not trying to overwrite and never was. I'm trying to import a DataFlow to a Workspace that does not have any DataFlow and the import command does not work, does not import the DataFlow and gives no feedback and no error on why it did not work. I can run the script in the original post, refresh Power BI in the Browser and the Workspace will have the imported DataSet (that command works) but no DataFlow (that command doesn't work).

The PowerBI API documentation says you cannot import via Service Principal, which is a massive thorn in my side. But in this case, I'm using "pbicli login" and my own user credentials, which I'm a Premium User, and know I can use the manual process of going to PowerBI in a Browser, logging in as the same user, finding the Workspace and "New > DataFlow > Import From File" (for unknown reasons, Power BI in the browser, the direct Import does not allow JSON) and verify the file I want to Import can be Imported without error, so there is nothing wrong with my file.
https://learn.microsoft.com/en-us/rest/api/power-bi/imports/post-import

**Comment by liprec** [comment]
Thanks for the extra information and the problem is that I can upload a new dataflow to a (non-premium) workspace.
Also, it doesn't look like it is related to any access issues as you can manually upload the dataflow via the webbrowser, so I do not have a clear solution.

But for the next release I will add additional response information, like the return id and response in case of an error.

**Comment by shanerowley-ds** [comment]
Thanks

**Comment by shanerowley-ds** [comment]
I have since worked out what the issue was. I had exported the DataFlow from another Workspace, changed a few things within. Then, when I import directly via Web Browser (which works without issue), several lines of attributes within the DataFlow get stealthily removed, without any feedback or me knowing this was happening. You can see the lines that get removed when you immediately export after importing the DataFlow. With these lines removed, the DataFlow can be imported via PowerBI CLI without issue. The lines are related to some residual "FullRefreshPolicyPartition" attributes as below.

```
"entities": [
    {
     ...
    "partitions": [
        {
            "name": "FullRefreshPolicyPartition",
            "refreshTime": "2022-03-31T01:03:59.6594514+00:00",
            "location": "https://wabiausebpcdsap1.blob.core.windows.net:443/806bd331-d3ab-422a-8e49-d6xxxxxxxxx25/containername.csv?snapshot=2022-03-31T01%3A03%3A59.6452287Z"
       }
```
