### ISSUE TITLE
[BUG] pbicli login silently fail for wrong credentials

### ISSUE THREAD

**Issue by azhozhin** [powerbi-cli/powerbi-cli#43]
**Versions**:

-   **pbicli version**: 1.3.2
-   **nodejs version**: 16.15.1
-   **os name/version**: Windows 10

**Describe the bug**
When using `pbicli login --service-principal ...` command just return without failing and reporting an issue. 
Consequent attempt to import powerbi (`pbicli import pbix ...`) report fail with *Not authenticated. Please run 'pbicli login'*

**To Reproduce**

1. run `pbicli login --service-principal --principal 0 --secret 0 --tennant 0 --verbose`
2. no error reported, exit code is 0 (zero)

**Expected behavior**
error should be reported that authentication is failed and non-zero exit code should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/416177/209147867-c5f857ac-534b-457c-b3d5-f5f420c9d4ce.png)

**PS**
This logic looks wrong to me (https://github.com/powerbi-cli/powerbi-cli/blob/develop/src/lib/auth.ts#L196) :
```
              const req = https.request(options, (res) => {
                if (res.statusCode === 200 || (res.statusCode === 400 && AuthFlow.DeviceCodeToken)) {
//                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    res.on("data", (data) => {
                        resolve(JSON.parse(data));
                    });
                } else {
                    reject("Unexpected error in authentication");
                }
            });
```

**Comment by liprec** [comment]
Thanks for the feedback and I will correct the authentication error flow as this is indeed not correct.

**Comment by liprec** [comment]
With version v1.3.3 this authentication error will exit with error code 1.

**Comment by azhozhin** [comment]
works like expected!
thank you very much.
