### ISSUE TITLE
[BUG] exit code zero if failure happened during report import

### ISSUE THREAD

**Issue by azhozhin** [powerbi-cli/powerbi-cli#44]
**Versions**:

-   **pbicli version**: 1.3.2
-   **nodejs version**: 16.15.1
-   **os name/version**: Windows 10

**Describe the bug**
During importing pbix file to non-existent workspace pbicli report error properly but return exit code 0 (zero)

**To Reproduce**

1. login to the service `pbicli --service-principal --principal xxx --secret yyy --tenant zzz`
2. run import of report to non-existent group/workspace `pbicli import pbix --workspace WWWW --file existing_report.pbix`
3. check error message: "No workspace found with name WWWW"
4. exit code 0 (zero)

**Expected behavior**
exit code should be non-zero

Looks like it is happening everywhere, could be an issue with exitCode handling if promise was rejected.

**Comment by liprec** [comment]
Thanks for the feedback and I will look at what is happening to the exit codes.

**Comment by liprec** [comment]
The latest version (v1.3.3) will exit with error code 2 if an error occurs.

**Comment by azhozhin** [comment]
works like expected! 
thanks a lot
